// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-DTEKK3kQME8DV8hbdAmOFlWQy7eKHlk',
    appId: '1:25984257291:web:93a734449ad0ae5079a60e',
    messagingSenderId: '25984257291',
    projectId: 'connect-coffee-dfbda',
    authDomain: 'connect-coffee-dfbda.firebaseapp.com',
    storageBucket: 'connect-coffee-dfbda.appspot.com',
    measurementId: 'G-KQ1VWE6H2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADLiyFL1zNhvPzRq3z6RECl7NiRccVL00',
    appId: '1:25984257291:android:849fb2018c510fb379a60e',
    messagingSenderId: '25984257291',
    projectId: 'connect-coffee-dfbda',
    storageBucket: 'connect-coffee-dfbda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuGHKC78oCkQw-0UptUt0hwO8NZj9f1Vk',
    appId: '1:25984257291:ios:ab0b09efa7521c5879a60e',
    messagingSenderId: '25984257291',
    projectId: 'connect-coffee-dfbda',
    storageBucket: 'connect-coffee-dfbda.appspot.com',
    iosBundleId: 'com.example.connectCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuGHKC78oCkQw-0UptUt0hwO8NZj9f1Vk',
    appId: '1:25984257291:ios:7ade9737118c00b979a60e',
    messagingSenderId: '25984257291',
    projectId: 'connect-coffee-dfbda',
    storageBucket: 'connect-coffee-dfbda.appspot.com',
    iosBundleId: 'com.example.connectCoffee.RunnerTests',
  );
}
